---
kind: pipeline
name: arm64_gcc_make

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: gcc
    COMMON_FLAGS: 'DYNAMIC_ARCH=1 TARGET=ARMV8 NUM_THREADS=32'
  commands: 
   - sudo apt update
   - sudo apt install python3-sphinx
   - git --version
   - cmake --version
   - make --version
   - gcc --version
   - cd ../..
   - curl -sL https://api.github.com/repos/flang-compiler/llvm/actions/workflows/build_llvm.yml/runs --output runs_llvm.json
   - curl -sL https://api.github.com/repos/flang-compiler/flang-driver/actions/workflows/build_flang-driver.yml/runs --output runs_flang-driver.json
   - wget --output-document artifacts_llvm `jq -r '.workflow_runs[0].artifacts_url?' runs_llvm.json`
   - wget --output-document artifacts_flang-driver `jq -r '.workflow_runs[0].artifacts_url?' runs_flang-driver.json`
   - # Retry with previous build in case no artifacts are available 
   - echo "cat artifacts_llvm"
   - cat artifacts_llvm
   - i="0"
   - while [ `jq -r '.total_count?' artifacts_llvm` == "0" ] && [ $i -lt 3 ]
   
